/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HueJFrame.java
 *
 * Created on 2010/9/5, ¤U¤È 02:18:41
 */
package auo.cms.applet.hue;

import java.text.*;
import java.util.*;

import javax.swing.*;

import org.jdesktop.beansbinding.*;
import shu.cms.*;
import shu.cms.colorspace.depend.*;
import shu.cms.colorspace.independ.*;

/**
 *
 * @author skyforce
 */
public class HueGameFrame
    extends javax.swing.JFrame {

  /** Creates new form HueJFrame */
  public HueGameFrame() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    jTextField_s = new javax.swing.JTextField();
    jTextField_h = new javax.swing.JTextField();
    jTextField_C = new javax.swing.JTextField();
    jTextField_b = new javax.swing.JTextField();
    jTextField_a = new javax.swing.JTextField();
    jTextField_L = new javax.swing.JTextField();
    jSlider_L = new javax.swing.JSlider();
    jSlider_a = new javax.swing.JSlider();
    jSlider_b = new javax.swing.JSlider();
    jSlider_C = new javax.swing.JSlider();
    jSlider_h = new javax.swing.JSlider();
    jSlider_s = new javax.swing.JSlider();
    jLabel13 = new javax.swing.JLabel();
    jPanel6 = new javax.swing.JPanel();
    jLabel12 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    jTextField_Chroma = new javax.swing.JTextField();
    jTextField_Value = new javax.swing.JTextField();
    jTextField_Saturation = new javax.swing.JTextField();
    jTextField_Hue = new javax.swing.JTextField();
    jSlider_Hue = new javax.swing.JSlider();
    jSlider_Saturation = new javax.swing.JSlider();
    jSlider_Value = new javax.swing.JSlider();
    jSlider_Chroma = new javax.swing.JSlider();
    jLabel20 = new javax.swing.JLabel();
    jTextField_Adj = new javax.swing.JTextField();
    jSlider_Adj = new javax.swing.JSlider();
    jPanel7 = new javax.swing.JPanel();
    jPanel8 = new javax.swing.JPanel();
    jLabel14 = new javax.swing.JLabel();
    jTextField_I = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    jSlider_I = new javax.swing.JSlider();
    jLabel16 = new javax.swing.JLabel();
    jTextField_P = new javax.swing.JTextField();
    jSlider_P = new javax.swing.JSlider();
    jLabel17 = new javax.swing.JLabel();
    jTextField_T = new javax.swing.JTextField();
    jSlider_T = new javax.swing.JSlider();
    jPanel4 = new javax.swing.JPanel();
    jLabel9 = new javax.swing.JLabel();
    jTextField_OrgHue = new javax.swing.JTextField();
    jSlider_OrgHue = new javax.swing.JSlider();
    jSlider_OrgSaturation = new javax.swing.JSlider();
    jTextField_OrgSaturation = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jTextField_OrgValue = new javax.swing.JTextField();
    jSlider_OrgValue = new javax.swing.JSlider();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jLabel_Left = new javax.swing.JLabel();
    jButton_RandomLeft = new javax.swing.JButton();
    jLabel_Right = new javax.swing.JLabel();
    jButton_RandomRight = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    jPanel1.setBackground(new java.awt.Color(255, 0, 51));
    jPanel1.setPreferredSize(new java.awt.Dimension(196, 196));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGap(0, 196, Short.MAX_VALUE)
        );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGap(0, 208, Short.MAX_VALUE)
        );

    jPanel2.setBackground(new java.awt.Color(67, 255, 51));
    jPanel2.setPreferredSize(new java.awt.Dimension(196, 196));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGap(0, 196, Short.MAX_VALUE)
        );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGap(0, 208, Short.MAX_VALUE)
        );

    jPanel3.setPreferredSize(new java.awt.Dimension(400, 327));

    jLabel4.setText("L");

    jLabel5.setText("a");

    jLabel6.setText("b");

    jLabel7.setText("C");

    jLabel8.setText("h");

    jLabel18.setText("s");

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.
        Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.
                                   UpdateStrategy.READ_WRITE, jSlider_s,
                                   org.
                                   jdesktop.beansbinding.ELProperty.create(
                                       "${value}"),
                                   jTextField_s,
                                   org.jdesktop.beansbinding.BeanProperty.
                                   create("text"));
    bindingGroup.addBinding(binding);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_h,
        org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField_h,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_C,
        org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField_C,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_b,
        org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField_b,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_a,
        org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField_a,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_L,
        org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField_L,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jSlider_L.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_LMouseReleased(evt);
      }
    });
    jSlider_L.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_LStateChanged(evt);
      }
    });

    jSlider_a.setMaximum(150);
    jSlider_a.setMinimum( -150);
    jSlider_a.setValue(0);
    jSlider_a.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_aMouseReleased(evt);
      }
    });
    jSlider_a.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_aStateChanged(evt);
      }
    });

    jSlider_b.setMaximum(150);
    jSlider_b.setMinimum( -150);
    jSlider_b.setValue(0);
    jSlider_b.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_bMouseReleased(evt);
      }
    });
    jSlider_b.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_bStateChanged(evt);
      }
    });

    jSlider_C.setMaximum(200);
    jSlider_C.setValue(0);
    jSlider_C.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_CMouseReleased(evt);
      }
    });
    jSlider_C.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_CStateChanged(evt);
      }
    });

    jSlider_h.setMaximum(359);
    jSlider_h.setValue(0);
    jSlider_h.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_hMouseReleased(evt);
      }
    });
    jSlider_h.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_hStateChanged(evt);
      }
    });

    jSlider_s.setMaximum(500);
    jSlider_s.setValue(0);
    jSlider_s.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_sMouseReleased(evt);
      }
    });
    jSlider_s.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_sStateChanged(evt);
      }
    });

    jLabel13.setText("Lab");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(jPanel5Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                      jPanel5Layout.createSequentialGroup()
                                      .addComponent(jLabel4)
                                      .addGap(18, 18, 18)
                                      .addComponent(jTextField_L,
        javax.swing.GroupLayout.PREFERRED_SIZE, 34,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.UNRELATED)
                                      .addComponent(jSlider_L,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                      .addGroup(jPanel5Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel18)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel7))
                                      .addGap(18, 18, 18)
                                      .addGroup(jPanel5Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.
        createSequentialGroup()
        .addComponent(jTextField_C, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                      javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSlider_C, javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel5Layout.
        createSequentialGroup()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.
        Alignment.TRAILING)
                  .addComponent(jTextField_s,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField_h,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.
                         LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel5Layout.
                  createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jSlider_s,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jSlider_h,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                      .addGroup(jPanel5Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                      .addGroup(jPanel5Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextField_a,
        javax.swing.GroupLayout.PREFERRED_SIZE, 34,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField_b,
        javax.swing.GroupLayout.PREFERRED_SIZE, 34,
        javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.UNRELATED)
                                      .addGroup(jPanel5Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addComponent(jSlider_a,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jSlider_b,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE))))
                  .addGap(208, 208, 208))
        .addComponent(jLabel13)
        );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
                  .addComponent(jLabel13)
                  .addGap(7, 7, 7)
                  .addGroup(jPanel5Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.
        swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(jLabel4)
                                      .addComponent(jTextField_L,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE))
                            .addComponent(jSlider_L,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.
                                   RELATED)
                  .addGroup(jPanel5Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                      .addComponent(jSlider_a,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE)
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addGroup(jPanel5Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel5Layout.
        createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jTextField_b, javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jLabel6))
                                                .addComponent(jSlider_b,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addGroup(jPanel5Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addComponent(jSlider_C,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel5Layout.
        createParallelGroup(javax.swing.
                            GroupLayout.Alignment.BASELINE)
        .addComponent(jTextField_C,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jLabel7)))
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addGroup(jPanel5Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addComponent(jSlider_h,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel5Layout.
        createParallelGroup(javax.swing.
                            GroupLayout.Alignment.BASELINE)
        .addComponent(jTextField_h,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jLabel8)))
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addGroup(jPanel5Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addComponent(jSlider_s,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel5Layout.
        createParallelGroup(javax.swing.
                            GroupLayout.Alignment.BASELINE)
        .addComponent(jTextField_s,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jLabel18))))
                            .addComponent(jLabel5)
                            .addComponent(jTextField_a,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE))
                  .addContainerGap(35, Short.MAX_VALUE))
        );

    jLabel12.setText("HSV");

    jLabel1.setText("H");

    jLabel2.setText("S");

    jLabel3.setText("V");

    jLabel19.setText("C");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_Chroma,
        org.jdesktop.beansbinding.ELProperty.create("${value}"),
        jTextField_Chroma, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_Value,
        org.jdesktop.beansbinding.ELProperty.create("${value}"),
        jTextField_Value, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_Saturation,
        org.jdesktop.beansbinding.ELProperty.create("${value}"),
        jTextField_Saturation,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_Hue,
        org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField_Hue,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jSlider_Hue.setMaximum(359);
    jSlider_Hue.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_HueMouseReleased(evt);
      }
    });
    jSlider_Hue.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_HueStateChanged(evt);
      }
    });

    jSlider_Saturation.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_SaturationMouseReleased(evt);
      }
    });
    jSlider_Saturation.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_SaturationStateChanged(evt);
      }
    });

    jSlider_Value.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_ValueMouseReleased(evt);
      }
    });
    jSlider_Value.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_ValueStateChanged(evt);
      }
    });

    jSlider_Chroma.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        jSlider_ChromaMousePressed(evt);
      }

      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_ChromaMouseReleased(evt);
      }
    });
    jSlider_Chroma.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_ChromaStateChanged(evt);
      }
    });

    jLabel20.setText("adj");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_Adj,
        org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField_Adj,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jSlider_Adj.setMaximum(10);
    jSlider_Adj.setValue(5);
    jSlider_Adj.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        jSlider_AdjMousePressed(evt);
      }

      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jSlider_AdjMouseReleased(evt);
      }
    });
    jSlider_Adj.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_AdjStateChanged(evt);
      }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                      .addGroup(jPanel6Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.
        GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
        .addComponent(jLabel20)
        .addGap(10, 10, 10)
        .addComponent(jTextField_Adj))
                                                .addGroup(javax.swing.
        GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.
        Alignment.TRAILING)
                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.
        swing.GroupLayout.Alignment.TRAILING)
                                      .addComponent(jLabel1)
                                      .addComponent(jLabel2)))
                  .addComponent(jLabel19))
        .addGap(18, 18, 18)
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.
        Alignment.TRAILING, false)
                  .addComponent(jTextField_Value,
                                javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jTextField_Hue,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 34,
                                Short.MAX_VALUE)
                  .addComponent(jTextField_Saturation)
                  .addComponent(jTextField_Chroma))))
                                      .addGroup(jPanel6Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.
        createSequentialGroup()
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.
        Alignment.LEADING)
                  .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jSlider_Value,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE)
                            .addGap(90, 90, 90))
                  .addComponent(jSlider_Chroma,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.
                         LayoutStyle.ComponentPlacement.RELATED))
                                                .addComponent(
        jSlider_Saturation,
        javax.swing.GroupLayout.
        PREFERRED_SIZE,
        javax.swing.GroupLayout.
        DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE)
                                                .addGroup(jPanel6Layout.
        createSequentialGroup()
        .addPreferredGap(javax.swing.
                         LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSlider_Hue,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.
                      PREFERRED_SIZE))
                                                .addGroup(jPanel6Layout.
        createSequentialGroup()
        .addPreferredGap(javax.swing.
                         LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSlider_Adj,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.
                      PREFERRED_SIZE))))
                            .addComponent(jLabel12))
                  .addContainerGap(26, Short.MAX_VALUE))
        );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
                  .addGap(13, 13, 13)
                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.TRAILING)
                            .addComponent(jSlider_Adj,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                      .addGroup(jPanel6Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.TRAILING)
                                                .addComponent(jSlider_Chroma,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel6Layout.
        createSequentialGroup()
        .addGroup(jPanel6Layout.
                  createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jSlider_Saturation,
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(jPanel6Layout.
                            createSequentialGroup()
                            .addGroup(jPanel6Layout.
                                      createParallelGroup(javax.swing.
        GroupLayout.Alignment.TRAILING)
                                      .addComponent(jSlider_Hue,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addGroup(jPanel6Layout.
                                                createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.
        LayoutStyle.ComponentPlacement.
        RELATED)
                                                .addGroup(jPanel6Layout.
        createParallelGroup(javax.swing.
                            GroupLayout.Alignment.BASELINE)
        .addComponent(jLabel1)
        .addComponent(jTextField_Hue,
                      javax.swing.GroupLayout.
                      PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.
                      PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.
                                             LayoutStyle.ComponentPlacement.
                                             RELATED)
                            .addGroup(jPanel6Layout.
                                      createParallelGroup(javax.swing.
        GroupLayout.Alignment.BASELINE)
                                      .addComponent(jTextField_Saturation,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(jLabel2))))
        .addGroup(jPanel6Layout.createParallelGroup(javax.
        swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jSlider_Value,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.
                                PREFERRED_SIZE)
                  .addGroup(jPanel6Layout.
                            createParallelGroup(javax.swing.
                                                GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Value,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE)))
        .addGap(7, 7, 7)
        .addGroup(jPanel6Layout.createParallelGroup(javax.
        swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jTextField_Chroma,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.
                                PREFERRED_SIZE)
                  .addComponent(jLabel19))))
                                      .addGap(7, 7, 7)
                                      .addGroup(jPanel6Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel20)
                                                .addComponent(jTextField_Adj,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE))))
                  .addContainerGap(35, Short.MAX_VALUE))
        );

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGap(0, 284, Short.MAX_VALUE)
        );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGap(0, 101, Short.MAX_VALUE)
        );

    jLabel14.setText("IPT");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_I,
        org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField_I,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jLabel15.setText("I");

    jLabel16.setText("P");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_P,
        org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField_P,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jLabel17.setText("T");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_T,
        org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField_T,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(jPanel8Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                      .addComponent(jLabel14)
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                      .addComponent(jLabel15)
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addComponent(jTextField_I,
        javax.swing.GroupLayout.PREFERRED_SIZE, 36,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addComponent(jSlider_I,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE)
                                      .addGap(66, 66, 66))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                      .addComponent(jLabel16)
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addComponent(jTextField_P,
        javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                      .addComponent(jSlider_P,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE)
                                      .addGap(66, 66, 66))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                      .addComponent(jLabel17)
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addComponent(jTextField_T,
        javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                      .addComponent(jSlider_T,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE)
                                      .addGap(66, 66, 66)))
                  .addGap(20, 20, 20))
        );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(jPanel8Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.TRAILING)
                            .addComponent(jSlider_T,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                      .addComponent(jLabel14)
                                      .addGroup(jPanel8Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel8Layout.
        createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jLabel15)
        .addComponent(jTextField_I, javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jSlider_I,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGroup(jPanel8Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addComponent(jSlider_P,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel8Layout.
        createParallelGroup(javax.swing.
                            GroupLayout.Alignment.BASELINE)
        .addComponent(jLabel16)
        .addComponent(jTextField_P,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE)))
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addGroup(jPanel8Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel17)
                                                .addComponent(jTextField_T,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE))))
                  .addContainerGap(22, Short.MAX_VALUE))
        );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                  jPanel3Layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                310, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.
                                   RELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                      .addComponent(jPanel8,
        javax.swing.GroupLayout.PREFERRED_SIZE, 286,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE,
        Short.MAX_VALUE)
                                      .addComponent(jPanel7,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE)
                                      .addGap(20, 20, 20))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                      .addComponent(jPanel5,
        javax.swing.GroupLayout.PREFERRED_SIZE, 338,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addContainerGap())))
        );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
                  .addGap(16, 16, 16)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                      .addComponent(jPanel8,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE)
                                      .addGap(76, 76, 76)
                                      .addComponent(jPanel5,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE))
                            .addComponent(jPanel6,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE)
                            .addComponent(jPanel7,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE)))
        );

    jLabel9.setText("H");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_OrgHue,
        org.jdesktop.beansbinding.ELProperty.create("${value}"),
        jTextField_OrgHue, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jSlider_OrgHue.setMaximum(359);
    jSlider_OrgHue.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_OrgHueStateChanged(evt);
      }
    });

    jSlider_OrgSaturation.addChangeListener(new javax.swing.event.
                                            ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_OrgSaturationStateChanged(evt);
      }
    });

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
        jSlider_OrgSaturation,
        org.jdesktop.beansbinding.ELProperty.create("${value}"),
        jTextField_OrgSaturation,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jLabel10.setText("S");

    jLabel11.setText("V");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.
        beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider_OrgValue,
        org.jdesktop.beansbinding.ELProperty.create("${value}"),
        jTextField_OrgValue,
        org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jSlider_OrgValue.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSlider_OrgValueStateChanged(evt);
      }
    });

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(jPanel4Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                      .addComponent(jScrollPane1,
        javax.swing.GroupLayout.PREFERRED_SIZE, 256,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                      .addContainerGap())
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                      .addGroup(jPanel4Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.
        createSequentialGroup()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.
        Alignment.TRAILING)
                  .addComponent(jLabel9)
                  .addComponent(jLabel10))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.
        Alignment.TRAILING)
                  .addComponent(jTextField_OrgHue,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTextField_OrgSaturation, 0, 0, Short.MAX_VALUE)))
                                                .addGroup(jPanel4Layout.
        createSequentialGroup()
        .addComponent(jLabel11)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextField_OrgValue, javax.swing.GroupLayout.DEFAULT_SIZE,
                      34, Short.MAX_VALUE)))
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addGroup(jPanel4Layout.
                                                createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                                                .addComponent(jSlider_OrgValue,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(
        jSlider_OrgSaturation,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE)
                                                .addComponent(jSlider_OrgHue,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE))
                                      .addGap(367, 367, 367))))
        );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
                                          LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
                  .addGap(13, 13, 13)
                  .addGroup(jPanel4Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.
        swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(jLabel9)
                                      .addComponent(jTextField_OrgHue,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE))
                            .addComponent(jSlider_OrgHue,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.
                                   RELATED)
                  .addGroup(jPanel4Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider_OrgSaturation,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.
        swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(jTextField_OrgSaturation,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE)
                                      .addComponent(jLabel10)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.
                                   RELATED)
                  .addGroup(jPanel4Layout.createParallelGroup(javax.swing.
        GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.
        swing.GroupLayout.Alignment.BASELINE)
                                      .addComponent(jLabel11)
                                      .addComponent(jTextField_OrgValue,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.
        PREFERRED_SIZE))
                            .addComponent(jSlider_OrgValue,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.
                                          PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.
                                   RELATED)
                  .addComponent(jScrollPane1,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 155,
                                Short.MAX_VALUE))
        );

    jLabel_Left.setText("(255,0,0)");

    jButton_RandomLeft.setText("Random");
    jButton_RandomLeft.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_RandomLeftActionPerformed(evt);
      }
    });

    jLabel_Right.setText("(0,255,0)");

    jButton_RandomRight.setText("Random");
    jButton_RandomRight.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_RandomRightActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.
        Alignment.TRAILING)
                            .addComponent(jPanel3,
                                          javax.swing.GroupLayout.Alignment.
                                          LEADING, 0, 708, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                      layout.createSequentialGroup()
                                      .addContainerGap()
                                      .addGroup(layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.
                                          LEADING, false)
                                                .addGroup(layout.
        createSequentialGroup()
        .addComponent(jLabel_Left)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                         javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton_RandomLeft))
                                                .addComponent(jPanel1,
        javax.swing.GroupLayout.PREFERRED_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.PREFERRED_SIZE))
                                      .addGroup(layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.
                                          LEADING, false)
                                                .addGroup(layout.
        createSequentialGroup()
        .addGap(8, 8, 8)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.
        createSequentialGroup()
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel_Right)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                         javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton_RandomRight)))
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addComponent(jPanel4,
        javax.swing.GroupLayout.PREFERRED_SIZE, 286,
        javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addContainerGap(18, Short.MAX_VALUE))
        );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.
        Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                      .addGroup(layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.
                                          LEADING)
                                                .addComponent(jPanel2,
        javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                                .addComponent(jPanel1,
        javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                                      .addPreferredGap(javax.swing.LayoutStyle.
        ComponentPlacement.RELATED)
                                      .addGroup(layout.createParallelGroup(
                                          javax.swing.GroupLayout.Alignment.
                                          BASELINE)
                                                .addComponent(jLabel_Left)
                                                .addComponent(
        jButton_RandomLeft)
                                                .addComponent(jLabel_Right)
                                                .addComponent(
        jButton_RandomRight))
                                      .addGap(22, 22, 22))
                            .addComponent(jPanel4,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          Short.MAX_VALUE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.
                                   RELATED)
                  .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                474, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap())
        );

    bindingGroup.bind();

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jSlider_OrgHueStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_OrgHueStateChanged
    int hue = this.jSlider_OrgHue.getValue();
    int saturation = this.jSlider_OrgSaturation.getValue();
    int value = this.jSlider_OrgValue.getValue();
    HSV hsv = new HSV(RGB.ColorSpace.SMPTE_C, new double[] {hue, saturation,
                      value});
    RGB rgb = hsv.toRGB();
    this.jPanel2.setBackground(rgb.getColor());
    rgb.changeMaxValue(RGB.MaxValue.Int8Bit);
    this.jLabel_Right.setText(rgb.toString());
  } //GEN-LAST:event_jSlider_OrgHueStateChanged

  private void jSlider_OrgSaturationStateChanged(javax.swing.event.ChangeEvent
                                                 evt) { //GEN-FIRST:event_jSlider_OrgSaturationStateChanged
    jSlider_OrgHueStateChanged(evt);
  } //GEN-LAST:event_jSlider_OrgSaturationStateChanged

  private void jSlider_OrgValueStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_OrgValueStateChanged
    jSlider_OrgHueStateChanged(evt);
  } //GEN-LAST:event_jSlider_OrgValueStateChanged

  private void jButton_RandomLeftActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton_RandomLeftActionPerformed
    java.util.Random random = new Random();
    int hue = (int) (random.nextDouble() * 360);
    int saturation = (int) (random.nextDouble() * 100);
    int value = (int) (random.nextDouble() * 100);
    this.jSlider_Hue.setValue(hue);
    this.jSlider_Saturation.setValue(saturation);
    this.jSlider_Value.setValue(value);
    adjustTimes = 0;
  } //GEN-LAST:event_jButton_RandomLeftActionPerformed

  private void jSlider_HueStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_HueStateChanged
    int hue = this.jSlider_Hue.getValue();
    int saturation = this.jSlider_Saturation.getValue();
    int value = this.jSlider_Value.getValue();
    //this.jSlider_Chroma.setValue(saturation);

    updateHSV(hue, saturation, value, false);
  } //GEN-LAST:event_jSlider_HueStateChanged

  private void jSlider_SaturationStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_SaturationStateChanged
    jSlider_HueStateChanged(evt);
  } //GEN-LAST:event_jSlider_SaturationStateChanged

  private void jSlider_ValueStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_ValueStateChanged
    jSlider_HueStateChanged(evt);
  } //GEN-LAST:event_jSlider_ValueStateChanged

  private void jSlider_aStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_aStateChanged
    int L = this.jSlider_L.getValue();
    int a = this.jSlider_a.getValue();
    int b = this.jSlider_b.getValue();
    updateLab(L, a, b);
  } //GEN-LAST:event_jSlider_aStateChanged

  private void jSlider_bStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_bStateChanged
    jSlider_aStateChanged(evt);
  } //GEN-LAST:event_jSlider_bStateChanged

  private void jSlider_LStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_LStateChanged
    jSlider_aStateChanged(evt);
  } //GEN-LAST:event_jSlider_LStateChanged

  private void jSlider_CStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_CStateChanged
    int L = this.jSlider_L.getValue();
    int C = this.jSlider_C.getValue();
    int h = this.jSlider_h.getValue();
    updateLCh(L, C, h);
  } //GEN-LAST:event_jSlider_CStateChanged

  private void jSlider_hStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_hStateChanged
    jSlider_CStateChanged(evt);
  } //GEN-LAST:event_jSlider_hStateChanged

  private void formWindowOpened(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_formWindowOpened
    jButton_RandomRightActionPerformed(null);
  } //GEN-LAST:event_formWindowOpened

  private void jButton_RandomRightActionPerformed(java.awt.event.ActionEvent
                                                  evt) { //GEN-FIRST:event_jButton_RandomRightActionPerformed
    java.util.Random random = new Random();
    int h = (int) (random.nextDouble() * 360);
    int s = (int) (random.nextDouble() * 100);
    int v = (int) (random.nextDouble() * 100);
    this.jSlider_OrgHue.setValue(h);
    this.jSlider_OrgSaturation.setValue(s);
    this.jSlider_OrgValue.setValue(v);
  } //GEN-LAST:event_jButton_RandomRightActionPerformed

  private void jSlider_HueMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_HueMouseReleased
    adjustTimes++;
  } //GEN-LAST:event_jSlider_HueMouseReleased

  private void jSlider_SaturationMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_SaturationMouseReleased
    adjustTimes++;
  } //GEN-LAST:event_jSlider_SaturationMouseReleased

  private void jSlider_ValueMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_ValueMouseReleased
    adjustTimes++;
  } //GEN-LAST:event_jSlider_ValueMouseReleased

  private void jSlider_LMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_LMouseReleased
    adjustTimes++;
  } //GEN-LAST:event_jSlider_LMouseReleased

  private void jSlider_aMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_aMouseReleased
    adjustTimes++;
  } //GEN-LAST:event_jSlider_aMouseReleased

  private void jSlider_bMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_bMouseReleased
    adjustTimes++;
  } //GEN-LAST:event_jSlider_bMouseReleased

  private void jSlider_CMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_CMouseReleased
    adjustTimes++;
  } //GEN-LAST:event_jSlider_CMouseReleased

  private void jSlider_hMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_hMouseReleased
    adjustTimes++;
  } //GEN-LAST:event_jSlider_hMouseReleased

  private void jSlider_sMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_sMouseReleased
    // TODO add your handling code here:
  } //GEN-LAST:event_jSlider_sMouseReleased

  private void jSlider_sStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_sStateChanged
    // TODO add your handling code here:
  } //GEN-LAST:event_jSlider_sStateChanged

  private void jSlider_ChromaMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_ChromaMouseReleased
    // TODO add your handling code here:
  } //GEN-LAST:event_jSlider_ChromaMouseReleased

  private void jSlider_ChromaStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_ChromaStateChanged
    /*int hue = this.jSlider_Hue.getValue();
             //int saturation = this.jSlider_Saturation.getValue();
             int value = this.jSlider_Value.getValue();

             int chroma = this.jSlider_Chroma.getValue();
             int adjust = chroma - chromaStartAdjust;
             //saturation += adjust;
             value += adjust / 5;

             updateHSV(hue, chroma, value, true);
             updateHSV(hue, chroma, value, false);*/
    if (!updating) {
      int hue = this.jSlider_Hue.getValue();
      //int saturation = this.jSlider_Saturation.getValue();
      //int value = this.jSlider_Value.getValue();


      int chroma = this.jSlider_Chroma.getValue();
      int adjustBase = this.jSlider_Adj.getValue();
      int adjust = chroma - chromaStartAdjust;
      //saturation += adjust;
      int value = valueStartAdjust + adjust / adjustBase;
      updateHSV(hue, chroma, value, true);
      updateHSV(hue, chroma, value, false);
    }
  } //GEN-LAST:event_jSlider_ChromaStateChanged

  private void jSlider_ChromaMousePressed(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_ChromaMousePressed
    chromaStartAdjust = this.jSlider_Chroma.getValue();
    valueStartAdjust = this.jSlider_Value.getValue();
  } //GEN-LAST:event_jSlider_ChromaMousePressed

  private void jSlider_AdjMousePressed(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_AdjMousePressed
    // TODO add your handling code here:
  } //GEN-LAST:event_jSlider_AdjMousePressed

  private void jSlider_AdjMouseReleased(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_jSlider_AdjMouseReleased
    // TODO add your handling code here:
  } //GEN-LAST:event_jSlider_AdjMouseReleased

  private void jSlider_AdjStateChanged(javax.swing.event.ChangeEvent evt) { //GEN-FIRST:event_jSlider_AdjStateChanged
    // TODO add your handling code here:
  } //GEN-LAST:event_jSlider_AdjStateChanged

  private boolean updating = false;
  private int adjustTimes = 0;
  private int chromaStartAdjust;
  private int valueStartAdjust;

  /**
   * Get the value of adjustTimes
   *
   * @return the value of adjustTimes
   */
  public int getAdjustTimes() {
    return adjustTimes;
  }

  /**
   * Get the value of updating
   *
   * @return the value of updating
   */
  public boolean isUpdating() {
    return updating;
  }

  private void updateHSV(int h, int s, int v, boolean hsvOnly) {
    if (updating) {
      return;
    }
    CIEXYZ whiteXYZ = RGB.toXYZ(RGB.White, RGBBase.ColorSpace.SMPTE_C);

    HSV hsv = new HSV(RGBBase.ColorSpace.SMPTE_C, new double[] {h, s, v});
    RGB rgb = hsv.toRGB();
    this.jPanel1.setBackground(rgb.getColor());
    rgb.changeMaxValue(RGB.MaxValue.Int8Bit);
    if (rgb.isLegal()) {
      this.jLabel_Left.setText(rgb.toString());
    }
    else {
      this.jLabel_Left.setText(rgb.toString() + " *");
    }

    updating = true;
    this.jSlider_Chroma.setValue(s);
    updating = false;

    if (hsvOnly) {
      updating = true;
      this.jSlider_Hue.setValue(h);
      this.jSlider_Saturation.setValue(s);
      this.jSlider_Value.setValue(v);

      updating = false;
    }
    else {
      CIEXYZ XYZ = rgb.toXYZ();

      CIELab Lab = new CIELab(XYZ, whiteXYZ);
      CIELCh LCh = new CIELCh(Lab);
      updating = true;
      this.jSlider_L.setValue( (int) Lab.L);
      this.jSlider_a.setValue( (int) Lab.a);
      this.jSlider_b.setValue( (int) Lab.b);
      this.jSlider_C.setValue( (int) LCh.C);
      this.jSlider_h.setValue( (int) LCh.h);
      this.jSlider_s.setValue( (int) (LCh.getSaturation() * 100));
      updating = false;
    }

    RGB rgb2 = new RGB(RGB.ColorSpace.SMPTE_C, this.jPanel2.getBackground());
    int dR = (int) (rgb.R - rgb2.R);
    int dG = (int) (rgb.G - rgb2.G);
    int dB = (int) (rgb.B - rgb2.B);
    CIEXYZ XYZ = rgb.toXYZ();
    CIEXYZ XYZ2 = rgb2.toXYZ();
    CIELab Lab = new CIELab(XYZ, whiteXYZ);
    CIELab Lab2 = new CIELab(XYZ2, whiteXYZ);
    DeltaE de = new DeltaE(Lab, Lab2);
    double[] dLCh00 = de.getCIE2000DeltaLCh();
    double dab00 = de.getCIE2000Deltaab();
    DecimalFormat df = new DecimalFormat("##.##");
    this.jTextArea1.setText("dR: " + dR + " dG: " + dG + " dB: " + dB + "\n"
                            + "de00: " + df.format(de.getCIE2000DeltaE()) +
                            "\n"
                            + "dC00: " + df.format(dLCh00[1]) + "\n"
                            + "dh00: " + df.format(dLCh00[2]) + "\n"
                            + "dab00: " + df.format(dab00) + "\n"
                            + "adj: " + adjustTimes);
  }

  private void updateLab(int L, int a, int b) {
    if (!updating) {
      CIEXYZ whiteXYZ = RGB.toXYZ(RGB.White, RGBBase.ColorSpace.SMPTE_C);
      CIELab Lab = new CIELab(L, a, b, whiteXYZ);
      CIELCh LCh = new CIELCh(Lab);

      updating = true;
      this.jSlider_C.setValue( (int) LCh.C);
      this.jSlider_h.setValue( (int) LCh.h);
      this.jSlider_s.setValue( (int) (LCh.getSaturation() * 100));
      updating = false;

      CIEXYZ XYZ = Lab.toXYZ();
      RGB rgb = new RGB(RGB.ColorSpace.SMPTE_C, XYZ);
      HSV hsv = new HSV(rgb);
      updateHSV( (int) hsv.H, (int) hsv.S, (int) hsv.V, true);
    }
  }

  private void updateLCh(int L, int C, int h) {
    if (!updating) {
      CIELCh LCh = new CIELCh(L, C, h);
      CIELab Lab = new CIELab(LCh);

      updating = true;
      this.jSlider_a.setValue( (int) Lab.a);
      this.jSlider_b.setValue( (int) Lab.b);
      this.jSlider_s.setValue( (int) (LCh.getSaturation() * 100));
      updating = false;

      CIEXYZ whiteXYZ = RGB.toXYZ(RGB.White, RGBBase.ColorSpace.SMPTE_C);
      CIEXYZ XYZ = CIELab.toXYZ(Lab, whiteXYZ);
      RGB rgb = new RGB(RGB.ColorSpace.SMPTE_C, XYZ);
      HSV hsv = new HSV(rgb);
      updateHSV( (int) hsv.H, (int) hsv.S, (int) hsv.V, true);
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new HueGameFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton_RandomLeft;
  private javax.swing.JButton jButton_RandomRight;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JLabel jLabel_Left;
  private javax.swing.JLabel jLabel_Right;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSlider jSlider_Adj;
  private javax.swing.JSlider jSlider_C;
  private javax.swing.JSlider jSlider_Chroma;
  private javax.swing.JSlider jSlider_Hue;
  private javax.swing.JSlider jSlider_I;
  private javax.swing.JSlider jSlider_L;
  private javax.swing.JSlider jSlider_OrgHue;
  private javax.swing.JSlider jSlider_OrgSaturation;
  private javax.swing.JSlider jSlider_OrgValue;
  private javax.swing.JSlider jSlider_P;
  private javax.swing.JSlider jSlider_Saturation;
  private javax.swing.JSlider jSlider_T;
  private javax.swing.JSlider jSlider_Value;
  private javax.swing.JSlider jSlider_a;
  private javax.swing.JSlider jSlider_b;
  private javax.swing.JSlider jSlider_h;
  private javax.swing.JSlider jSlider_s;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextField jTextField_Adj;
  private javax.swing.JTextField jTextField_C;
  private javax.swing.JTextField jTextField_Chroma;
  private javax.swing.JTextField jTextField_Hue;
  private javax.swing.JTextField jTextField_I;
  private javax.swing.JTextField jTextField_L;
  private javax.swing.JTextField jTextField_OrgHue;
  private javax.swing.JTextField jTextField_OrgSaturation;
  private javax.swing.JTextField jTextField_OrgValue;
  private javax.swing.JTextField jTextField_P;
  private javax.swing.JTextField jTextField_Saturation;
  private javax.swing.JTextField jTextField_T;
  private javax.swing.JTextField jTextField_Value;
  private javax.swing.JTextField jTextField_a;
  private javax.swing.JTextField jTextField_b;
  private javax.swing.JTextField jTextField_h;
  private javax.swing.JTextField jTextField_s;
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;
  // End of variables declaration//GEN-END:variables
}
