//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.05.04 at 12:51:40 下午 CST
//


package shu.cms.colorformat.cxf;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.*;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
         "value"
})
@XmlRootElement(name = "DensityData")
public class DensityData {

  @XmlAttribute(name = "Filter")
  @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
  protected String filter;

  @XmlValue
  protected String value;

  /**
   * Gets the value of the filter property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getFilter() {
    return filter;
  }

  /**
   * Sets the value of the filter property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setFilter(String value) {
    this.filter = value;
  }

  /**
   * Gets the value of the value property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getvalue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setvalue(String value) {
    this.value = value;
  }

}
