//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.05.04 at 12:51:40 下午 CST
//


package shu.cms.colorformat.cxf;

import javax.xml.bind.annotation.*;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
         "name",
         "description",
         "creator",
         "created",
         "modified",
         "additionalData",
         "iccData"
})
@XmlRootElement(name = "ICC-Profile")
public class ICCProfile {

  @XmlElement(name = "Name")
  protected String name;

  @XmlElement(name = "Description")
  protected String description;

  @XmlElement(name = "Creator")
  protected String creator;

  @XmlElement(name = "Created")
  protected String created;

  @XmlElement(name = "Modified")
  protected String modified;

  @XmlElement(name = "AdditionalData")
  protected AdditionalData additionalData;

  @XmlElement(name = "ICC-Data")
  protected ICCData iccData;

  /**
   * Gets the value of the name property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the description property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the creator property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getCreator() {
    return creator;
  }

  /**
   * Sets the value of the creator property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setCreator(String value) {
    this.creator = value;
  }

  /**
   * Gets the value of the created property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getCreated() {
    return created;
  }

  /**
   * Sets the value of the created property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setCreated(String value) {
    this.created = value;
  }

  /**
   * Gets the value of the modified property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getModified() {
    return modified;
  }

  /**
   * Sets the value of the modified property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setModified(String value) {
    this.modified = value;
  }

  /**
   * Gets the value of the additionalData property.
   *
   * @return
   *     possible object is
   *     {@link AdditionalData }
   *
   */
  public AdditionalData getAdditionalData() {
    return additionalData;
  }

  /**
   * Sets the value of the additionalData property.
   *
   * @param value
   *     allowed object is
   *     {@link AdditionalData }
   *
   */
  public void setAdditionalData(AdditionalData value) {
    this.additionalData = value;
  }

  /**
   * Gets the value of the iccData property.
   *
   * @return
   *     possible object is
   *     {@link ICCData }
   *
   */
  public ICCData getICCData() {
    return iccData;
  }

  /**
   * Sets the value of the iccData property.
   *
   * @param value
   *     allowed object is
   *     {@link ICCData }
   *
   */
  public void setICCData(ICCData value) {
    this.iccData = value;
  }

}
