//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.05.04 at 12:51:40 下午 CST
//


package shu.cms.colorformat.cxf;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.*;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ICC-ProfileLink")
public class ICCProfileLink {

  @XmlAttribute(name = "UniqueID")
  @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
  protected String uniqueID;

  /**
   * Gets the value of the uniqueID property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getUniqueID() {
    return uniqueID;
  }

  /**
   * Sets the value of the uniqueID property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setUniqueID(String value) {
    this.uniqueID = value;
  }

}
