//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.05.04 at 12:51:40 下午 CST
//


package shu.cms.colorformat.cxf;

import javax.xml.bind.annotation.*;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
         "spectrum",
         "colorVector",
         "deviceColor",
         "namedColor",
         "density",
         "recipe"
})
@XmlRootElement(name = "SampleAttribute")
public class SampleAttribute {

  @XmlElement(name = "Spectrum")
  protected Spectrum spectrum;

  @XmlElement(name = "ColorVector")
  protected ColorVector colorVector;

  @XmlElement(name = "DeviceColor")
  protected DeviceColor deviceColor;

  @XmlElement(name = "NamedColor")
  protected NamedColor namedColor;

  @XmlElement(name = "Density")
  protected Density density;

  @XmlElement(name = "Recipe")
  protected Recipe recipe;

  /**
   * Gets the value of the spectrum property.
   *
   * @return
   *     possible object is
   *     {@link Spectrum }
   *
   */
  public Spectrum getSpectrum() {
    return spectrum;
  }

  /**
   * Sets the value of the spectrum property.
   *
   * @param value
   *     allowed object is
   *     {@link Spectrum }
   *
   */
  public void setSpectrum(Spectrum value) {
    this.spectrum = value;
  }

  /**
   * Gets the value of the colorVector property.
   *
   * @return
   *     possible object is
   *     {@link ColorVector }
   *
   */
  public ColorVector getColorVector() {
    return colorVector;
  }

  /**
   * Sets the value of the colorVector property.
   *
   * @param value
   *     allowed object is
   *     {@link ColorVector }
   *
   */
  public void setColorVector(ColorVector value) {
    this.colorVector = value;
  }

  /**
   * Gets the value of the deviceColor property.
   *
   * @return
   *     possible object is
   *     {@link DeviceColor }
   *
   */
  public DeviceColor getDeviceColor() {
    return deviceColor;
  }

  /**
   * Sets the value of the deviceColor property.
   *
   * @param value
   *     allowed object is
   *     {@link DeviceColor }
   *
   */
  public void setDeviceColor(DeviceColor value) {
    this.deviceColor = value;
  }

  /**
   * Gets the value of the namedColor property.
   *
   * @return
   *     possible object is
   *     {@link NamedColor }
   *
   */
  public NamedColor getNamedColor() {
    return namedColor;
  }

  /**
   * Sets the value of the namedColor property.
   *
   * @param value
   *     allowed object is
   *     {@link NamedColor }
   *
   */
  public void setNamedColor(NamedColor value) {
    this.namedColor = value;
  }

  /**
   * Gets the value of the density property.
   *
   * @return
   *     possible object is
   *     {@link Density }
   *
   */
  public Density getDensity() {
    return density;
  }

  /**
   * Sets the value of the density property.
   *
   * @param value
   *     allowed object is
   *     {@link Density }
   *
   */
  public void setDensity(Density value) {
    this.density = value;
  }

  /**
   * Gets the value of the recipe property.
   *
   * @return
   *     possible object is
   *     {@link Recipe }
   *
   */
  public Recipe getRecipe() {
    return recipe;
  }

  /**
   * Sets the value of the recipe property.
   *
   * @param value
   *     allowed object is
   *     {@link Recipe }
   *
   */
  public void setRecipe(Recipe value) {
    this.recipe = value;
  }

}
