//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.05.04 at 12:51:40 ¤U¤È CST
//


package shu.cms.colorformat.cxf;

import java.util.*;
import javax.xml.bind.annotation.*;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
         "id",
         "attribute",
         "spectrum"
})
@XmlRootElement(name = "Conditions")
public class Conditions {

  @XmlElement(name = "ID")
  protected String id;

  @XmlElement(name = "Attribute")
  protected List<Attribute> attribute;

  @XmlElement(name = "Spectrum")
  protected Spectrum spectrum;

  /**
   * Gets the value of the id property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getID() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setID(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the attribute property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the attribute property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getAttribute().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link Attribute }
   *
   *
   */
  public List<Attribute> getAttribute() {
    if (attribute == null) {
      attribute = new ArrayList<Attribute> ();
    }
    return this.attribute;
  }

  /**
   * Gets the value of the spectrum property.
   *
   * @return
   *     possible object is
   *     {@link Spectrum }
   *
   */
  public Spectrum getSpectrum() {
    return spectrum;
  }

  /**
   * Sets the value of the spectrum property.
   *
   * @param value
   *     allowed object is
   *     {@link Spectrum }
   *
   */
  public void setSpectrum(Spectrum value) {
    this.spectrum = value;
  }

}
