//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.05.04 at 12:51:40 ¤U¤È CST
//


package shu.cms.colorformat.cxf;

import javax.xml.bind.annotation.*;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
   *
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link ColorVector }
   *
   */
  public ColorVector createColorVector() {
    return new ColorVector();
  }

  /**
   * Create an instance of {@link AdditionalData }
   *
   */
  public AdditionalData createAdditionalData() {
    return new AdditionalData();
  }

  /**
   * Create an instance of {@link NamedColor }
   *
   */
  public NamedColor createNamedColor() {
    return new NamedColor();
  }

  /**
   * Create an instance of {@link Conditions }
   *
   */
  public Conditions createConditions() {
    return new Conditions();
  }

  /**
   * Create an instance of {@link Sample }
   *
   */
  public Sample createSample() {
    return new Sample();
  }

  /**
   * Create an instance of {@link ICCProfileLink }
   *
   */
  public ICCProfileLink createICCProfileLink() {
    return new ICCProfileLink();
  }

  /**
   * Create an instance of {@link Attribute }
   *
   */
  public Attribute createAttribute() {
    return new Attribute();
  }

  /**
   * Create an instance of {@link Spectrum }
   *
   */
  public Spectrum createSpectrum() {
    return new Spectrum();
  }

  /**
   * Create an instance of {@link ICCProfile }
   *
   */
  public ICCProfile createICCProfile() {
    return new ICCProfile();
  }

  /**
   * Create an instance of {@link Components }
   *
   */
  public Components createComponents() {
    return new Components();
  }

  /**
   * Create an instance of {@link SampleSet }
   *
   */
  public SampleSet createSampleSet() {
    return new SampleSet();
  }

  /**
   * Create an instance of {@link BinaryObject }
   *
   */
  public BinaryObject createBinaryObject() {
    return new BinaryObject();
  }

  /**
   * Create an instance of {@link ICCData }
   *
   */
  public ICCData createICCData() {
    return new ICCData();
  }

  /**
   * Create an instance of {@link Density }
   *
   */
  public Density createDensity() {
    return new Density();
  }

  /**
   * Create an instance of {@link CXF }
   *
   */
  public CXF createCXF() {
    return new CXF();
  }

  /**
   * Create an instance of {@link DeviceColor }
   *
   */
  public DeviceColor createDeviceColor() {
    return new DeviceColor();
  }

  /**
   * Create an instance of {@link SampleAttribute }
   *
   */
  public SampleAttribute createSampleAttribute() {
    return new SampleAttribute();
  }

  /**
   * Create an instance of {@link Recipe }
   *
   */
  public Recipe createRecipe() {
    return new Recipe();
  }

  /**
   * Create an instance of {@link Value }
   *
   */
  public Value createValue() {
    return new Value();
  }

  /**
   * Create an instance of {@link DensityData }
   *
   */
  public DensityData createDensityData() {
    return new DensityData();
  }

}
